server:
  port: 8082
spring:
  application:
    name: user-consumer # 应用名称

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true # 当其它服务获取地址时提供ip而不是hostname
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    instance-id: user-consumer #指定在eureka中显示的实例名称
info:
  app.name: user-consumer
  app.desc: 这是一个用户客户端服务
